# Generated by Django 4.2.13 on 2026-02-19 08:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^(\\+254|0)[0-9]{9}$', 'Enter a valid Kenyan phone number')])),
                ('national_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('county', models.CharField(choices=[('Kakamega', 'Kakamega'), ('Trans Nzoia', 'Trans Nzoia'), ('Bungoma', 'Bungoma')], default='Kakamega', max_length=50)),
                ('ward', models.CharField(choices=[('Matungu', 'Matungu'), ('Mumias', 'Mumias'), ('Navakholo', 'Navakholo'), ('Lurambi', 'Lurambi')], default='Matungu', max_length=50)),
                ('user_type', models.CharField(choices=[('Applicant', 'Applicant'), ('Ward_Admin', 'Ward Admin'), ('CDF_Admin', 'CDF Admin'), ('Super_Admin', 'Super Admin')], default='Applicant', max_length=20)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('Application_Submitted', 'Application Submitted'), ('Application_Approved', 'Application Approved'), ('Application_Rejected', 'Application Rejected'), ('Review_Added', 'Review Added'), ('Status_Update', 'Status Update'), ('System_Message', 'System Message')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_type', models.CharField(choices=[('Ward_Admin', 'Ward Admin'), ('CDF_Admin', 'CDF Admin')], help_text='Select the level of administration', max_length=20)),
                ('ward', models.CharField(choices=[('Matungu', 'Matungu'), ('Mumias', 'Mumias'), ('Navakholo', 'Navakholo'), ('Lurambi', 'Lurambi')], max_length=50)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('permissions', models.JSONField(default=list, help_text='List of specific permissions')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_admin_roles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_date'],
                'unique_together': {('user', 'role_type', 'ward')},
            },
        ),
    ]
