# Generated by Django 6.0.2 on 2026-02-20 23:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_national_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adminrole',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='adminrole',
            name='ward',
            field=models.CharField(choices=[('Mayoni', 'Mayoni'), ('Kholera', 'Kholera'), ('Khalaba', 'Khalaba'), ('Koyonzo', 'Koyonzo'), ('Namamali', 'Namamali')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='national_id',
            field=models.CharField(blank=True, help_text='National ID number - must be unique to prevent duplicate accounts', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ward',
            field=models.CharField(choices=[('Mayoni', 'Mayoni'), ('Kholera', 'Kholera'), ('Khalaba', 'Khalaba'), ('Koyonzo', 'Koyonzo'), ('Namamali', 'Namamali')], default='Matungu', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='adminrole',
            constraint=models.UniqueConstraint(fields=('user',), name='one_admin_per_user'),
        ),
    ]
