# Generated by Django 4.2.13 on 2026-02-19 08:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Draft', 'Draft - Not Submitted'), ('Submitted', 'Submitted - Under Review'), ('Under_Review', 'Under Review - Admin Reviewing'), ('Needs_Clarification', 'Needs Clarification'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Appeal', 'Under Appeal Review')], default='Draft', max_length=50)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('submitted_date', models.DateTimeField(blank=True, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('national_id', models.CharField(max_length=20)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Other', 'Other')], default='Single', max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('family_income', models.DecimalField(decimal_places=2, help_text='Annual family income in KES', max_digits=12)),
                ('income_source', models.CharField(blank=True, max_length=255)),
                ('number_of_dependents', models.IntegerField(default=0)),
                ('other_siblings_in_school', models.IntegerField(default=0)),
                ('kcse_score', models.CharField(blank=True, help_text='KCSE aggregate score', max_length=10)),
                ('stream', models.CharField(blank=True, help_text='Science/Arts/Commercial', max_length=50)),
                ('admission_letter_number', models.CharField(blank=True, max_length=100)),
                ('motivation_letter', models.TextField(blank=True, help_text='Why you need this bursary')),
                ('expected_challenges', models.TextField(blank=True, help_text='Financial challenges you face')),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='schools.campus')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='schools.program')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': (('can_approve_applications', 'Can approve applications'), ('can_reject_applications', 'Can reject applications'), ('can_comment_applications', 'Can comment on applications'), ('can_review_applications', 'Can review applications')),
            },
        ),
        migrations.CreateModel(
            name='ApplicationReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_score', models.IntegerField(default=0, help_text='Score out of 100')),
                ('financial_need_score', models.IntegerField(default=0, help_text='Score out of 100')),
                ('supporting_documents_score', models.IntegerField(default=0, help_text='Score out of 100')),
                ('overall_score', models.IntegerField(default=0, help_text='Final score out of 100')),
                ('review_status', models.CharField(choices=[('Pending', 'Pending Review'), ('In_Progress', 'In Progress'), ('Completed', 'Review Completed')], default='Pending', max_length=20)),
                ('recommendation', models.CharField(blank=True, choices=[('Approve', 'Approve'), ('Reject', 'Reject'), ('Clarify', 'Needs Clarification')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True, help_text='For admin use only')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='applications.application')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal comment not visible to applicant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='applications.application')),
                ('commented_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_level', models.CharField(choices=[('Ward_Admin', 'Ward Admin'), ('CDF_Admin', 'CDF Admin'), ('Super_Admin', 'Super Admin')], max_length=20)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, help_text='Approved amount in KES', max_digits=10, null=True)),
                ('approved_date', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='applications.application')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-approved_date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('KCSE_Certificate', 'KCSE Certificate'), ('Admission_Letter', 'Admission Letter'), ('Birth_Certificate', 'Birth Certificate'), ('National_ID', 'National ID'), ('Clearance_Letter', 'School Clearance Letter'), ('Fee_Structure', 'School Fee Structure'), ('Income_Evidence', 'Income Evidence (Pay slip/Business document)'), ('Parents_ID', "Parent's ID"), ('Other', 'Other Document')], max_length=50)),
                ('file', models.FileField(help_text='Max file size: 5MB', upload_to='applications/documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'doc', 'docx', 'xls', 'xlsx'])])),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['document_type', '-uploaded_date'],
                'unique_together': {('application', 'document_type')},
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant', 'status'], name='application_applica_b6966f_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['school', 'status'], name='application_school__f0674b_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', 'submitted_date'], name='application_status_a9baff_idx'),
        ),
    ]
