# Generated by Django 6.0.3 on 2026-03-06 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='schools.campus'),
        ),
        migrations.AddField(
            model_name='application',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schools.program'),
        ),
        migrations.AddField(
            model_name='application',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schools.school'),
        ),
        migrations.AddField(
            model_name='applicationapproval',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='applications.application'),
        ),
        migrations.AddField(
            model_name='applicationapproval',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application'),
        ),
        migrations.AddField(
            model_name='applicationreview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='applications.application'),
        ),
        migrations.AddField(
            model_name='applicationreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
