# Generated by Django 4.2.13 on 2026-02-19 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('constituency', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['county', 'constituency', 'name'],
                'indexes': [models.Index(fields=['county', 'constituency'], name='application_county_944fa1_idx')],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='ward',
            field=models.ForeignKey(blank=True, help_text="Applicant's ward/constituency", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='applications.ward'),
        ),
    ]
