# Generated by Django 6.0.3 on 2026-03-10 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
        ('schools', '0003_rename_tvet_to_ttc_optional_contact_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='course_name',
            field=models.CharField(blank=True, help_text='Name of your course/programme', max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='schools.program'),
        ),
    ]
