# Generated by Django 6.0.3 on 2026-03-10 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_add_course_name_nullable_program'),
        ('schools', '0003_rename_tvet_to_ttc_optional_contact_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BursarySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2025/2026', help_text='e.g. 2025/2026', max_length=20)),
                ('application_deadline', models.DateTimeField(blank=True, help_text='Deadline for submitting bursary applications', null=True)),
                ('is_accepting_applications', models.BooleanField(default=True, help_text='Uncheck to close applications even before the deadline')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum bursary amount an applicant can request', max_digits=10, null=True)),
                ('announcement', models.TextField(blank=True, default='', help_text='Optional notice shown on the dashboard (HTML allowed)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bursary Settings',
                'verbose_name_plural': 'Bursary Settings',
            },
        ),
        migrations.AlterField(
            model_name='application',
            name='admission_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='amount_requested',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='course_name',
            field=models.CharField(blank=True, default='', help_text='Name of your course/programme', max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='family_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='reason',
            field=models.TextField(blank=True, default='', help_text='Reason for applying'),
        ),
        migrations.AlterField(
            model_name='application',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='schools.school'),
        ),
        migrations.AlterField(
            model_name='application',
            name='year_of_study',
            field=models.CharField(blank=True, choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year'), ('5', 'Fifth Year'), ('6', 'Sixth Year')], default='', max_length=1),
        ),
    ]
