# Generated by Django 4.2.13 on 2026-02-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_ward_application_ward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='admission_letter_number',
        ),
        migrations.RemoveField(
            model_name='application',
            name='kcse_score',
        ),
        migrations.RemoveField(
            model_name='application',
            name='stream',
        ),
        migrations.AddField(
            model_name='application',
            name='course_name',
            field=models.CharField(blank=True, help_text='Course/Program you are studying', max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='is_orphan',
            field=models.BooleanField(default=False, help_text='Check if you are an orphan'),
        ),
        migrations.AddField(
            model_name='application',
            name='year_of_study',
            field=models.CharField(blank=True, choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year'), ('5th Year', '5th Year'), ('6th Year', '6th Year')], help_text='Current year of study', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='document_type',
            field=models.CharField(choices=[('Admission_Letter', 'Admission Letter'), ('Birth_Certificate', 'Birth Certificate'), ('National_ID', 'National ID'), ('Fee_Structure', 'School Fee Structure'), ('Parents_ID', "Parent's ID"), ('Death_Certificate', 'Death Certificate (For Orphans)'), ('Other', 'Other Document')], max_length=50),
        ),
    ]
