# Generated by Django 4.2.13 on 2026-02-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_remove_application_admission_letter_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='program_level',
            field=models.CharField(blank=True, choices=[('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Higher Diploma', 'Higher Diploma'), ('Degree', 'Degree (Bachelor)'), ('Masters', 'Masters'), ('PhD', 'PhD/Doctorate')], help_text='Level of study program', max_length=50),
        ),
    ]
