# Generated by Django 6.0.2 on 2026-02-20 23:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_application_program_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_registration_open', models.BooleanField(default=True, help_text='Toggle registration status')),
                ('deadline_date', models.DateTimeField(blank=True, help_text='Registration deadline date and time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registration Settings',
                'verbose_name_plural': 'Registration Settings',
            },
        ),
    ]
