from django.core.management.base import BaseCommand
from schools.models import School, Campus


class Command(BaseCommand):
    help = 'Populate database with all Kenyan universities, colleges, polytechnics, and TTCs'

    def handle(self, *args, **kwargs):
        self.stdout.write('Populating schools...')
        created_total = 0

        # ─────────────────────────────────────────────────────────
        # UNIVERSITIES
        # ─────────────────────────────────────────────────────────
        universities = [
            ('Chuka University', 'UNI-001', 'Tharaka Nithi'),
            ('Co-operative University of Kenya', 'UNI-002', 'Nairobi'),
            ('Dedan Kimathi University of Technology', 'UNI-003', 'Nyeri'),
            ('Egerton University', 'UNI-004', 'Nakuru'),
            ('Garissa University', 'UNI-005', 'Garissa'),
            ('Jaramogi Oginga Odinga University of Science and Technology', 'UNI-006', 'Siaya'),
            ('Jomo Kenyatta University of Agriculture and Technology', 'UNI-007', 'Kiambu'),
            ('Kabarnet University College', 'UNI-008', 'Baringo'),
            ('Karatina University', 'UNI-009', 'Nyeri'),
            ('Koitaleel Samoei University College', 'UNI-010', 'Nandi'),
            ('Kenyatta University', 'UNI-011', 'Nairobi'),
            ('Kibabii University', 'UNI-012', 'Bungoma'),
            ('Kirinyaga University', 'UNI-013', 'Kirinyaga'),
            ('Kisii University', 'UNI-014', 'Kisii'),
            ('Laikipia University', 'UNI-015', 'Laikipia'),
            ('Maasai Mara University', 'UNI-016', 'Narok'),
            ('Machakos University', 'UNI-017', 'Machakos'),
            ('Maseno University', 'UNI-018', 'Kisumu'),
            ('Masinde Muliro University of Science and Technology', 'UNI-019', 'Kakamega'),
            ('Meru University of Science and Technology', 'UNI-020', 'Meru'),
            ('Moi University', 'UNI-021', 'Uasin Gishu'),
            ('Multimedia University of Kenya', 'UNI-022', 'Nairobi'),
            ("Murang'a University of Technology", 'UNI-023', "Murang'a"),
            ('Nyandarua University College', 'UNI-024', 'Nyandarua'),
            ('Open University of Kenya', 'UNI-025', 'Nairobi'),
            ('Pwani University', 'UNI-026', 'Kilifi'),
            ('Rongo University', 'UNI-027', 'Migori'),
            ('South Eastern Kenya University', 'UNI-028', 'Kitui'),
            ('Taita Taveta University', 'UNI-029', 'Taita Taveta'),
            ('Technical University of Kenya', 'UNI-030', 'Nairobi'),
            ('Technical University of Mombasa', 'UNI-031', 'Mombasa'),
            ('University of Eldoret', 'UNI-032', 'Uasin Gishu'),
            ('University of Embu', 'UNI-033', 'Embu'),
            ('University of Kabianga', 'UNI-034', 'Kericho'),
            ('University of Nairobi', 'UNI-035', 'Nairobi'),
            ('Alupe University College', 'UNI-036', 'Busia'),
            ('Kaimosi Friends University College', 'UNI-037', 'Vihiga'),
            ('Mama Ngina University College', 'UNI-038', 'Mombasa'),
            ('Tom Mboya University College', 'UNI-039', 'Homa Bay'),
            ('Turkana University College', 'UNI-040', 'Turkana'),
            ('Bomet University College', 'UNI-041', 'Bomet'),
            ('Tharaka University College', 'UNI-042', 'Tharaka Nithi'),
            ('Africa International University', 'UNI-043', 'Nairobi'),
            ('African Leadership University', 'UNI-044', 'Nairobi'),
            ('Africa Nazarene University', 'UNI-045', 'Kajiado'),
            ('Amref International University', 'UNI-046', 'Nairobi'),
            ('Catholic University of Eastern Africa', 'UNI-047', 'Nairobi'),
            ('Daystar University', 'UNI-048', 'Nairobi'),
            ('Great Lakes University of Kisumu', 'UNI-049', 'Kisumu'),
            ('Gretsa University', 'UNI-050', 'Kiambu'),
            ('International Leadership University', 'UNI-051', 'Nairobi'),
            ('Islamic University of Kenya', 'UNI-052', 'Nairobi'),
            ('Kabarak University', 'UNI-053', 'Nakuru'),
            ('KAG East University', 'UNI-054', 'Nairobi'),
            ('KCA University', 'UNI-055', 'Nairobi'),
            ('Kenya Highlands University', 'UNI-056', 'Kericho'),
            ('Kenya Methodist University', 'UNI-057', 'Meru'),
            ("Kiriri Women's University of Science and Technology", 'UNI-058', 'Nairobi'),
            ('Lukenya University', 'UNI-059', 'Machakos'),
            ('Marist International University College', 'UNI-060', 'Nairobi'),
            ('Mount Kenya University', 'UNI-061', 'Nyeri'),
            ('Pan Africa Christian University', 'UNI-062', 'Nairobi'),
            ('Pioneer International University', 'UNI-063', 'Nairobi'),
            ('Riara University', 'UNI-064', 'Nairobi'),
            ('Scott Christian University', 'UNI-065', 'Meru'),
            ("St Paul's University", 'UNI-066', 'Kiambu'),
            ('Tangaza University', 'UNI-067', 'Nairobi'),
            ('The East Africa University', 'UNI-068', 'Embu'),
            ('The Management University of Africa', 'UNI-069', 'Nairobi'),
            ('The Presbyterian University of East Africa', 'UNI-070', 'Nairobi'),
            ('United States International University', 'UNI-071', 'Nairobi'),
            ('University of Eastern Africa Baraton', 'UNI-072', 'Nandi'),
            ('Uzima University College', 'UNI-073', 'Kisumu'),
            ('Umma University', 'UNI-074', 'Kajiado'),
            ('Zetech University', 'UNI-075', 'Nairobi'),
        ]

        for name, code, county in universities:
            school, created = School.objects.get_or_create(
                registration_number=code,
                defaults={'name': name, 'school_type': 'university', 'county': county}
            )
            if created:
                Campus.objects.get_or_create(school=school, name='Main Campus',
                                             defaults={'location': county, 'is_main': True})
                created_total += 1

        self.stdout.write(self.style.SUCCESS(f'Universities done.'))

        # ─────────────────────────────────────────────────────────
        # COLLEGES
        # ─────────────────────────────────────────────────────────
        colleges = [
            ('Ahmed Shahame Mwidani Technical and Vocational College', 'COL-001', 'Mombasa'),
            ('Aldai Technical Training Institute', 'COL-002', 'Nandi'),
            ('Alupe University TVET Institute', 'COL-003', 'Busia'),
            ('Bahati Institute of Business and Administration', 'COL-004', 'Nakuru'),
            ('Balambala Technical and Vocational College', 'COL-005', 'Garissa'),
            ('Bandari Maritime Academy', 'COL-006', 'Mombasa'),
            ('Belgut Technical and Vocational College', 'COL-007', 'Kericho'),
            ('Bomet Central Technical and Vocational College', 'COL-008', 'Bomet'),
            ('Bondo Technical Training Institute', 'COL-009', 'Siaya'),
            ('Borabu Technical Training Institute', 'COL-010', 'Nyamira'),
            ('Bukura Agricultural College', 'COL-011', 'Kakamega'),
            ('Bungoma North Technical and Vocational College', 'COL-012', 'Bungoma'),
            ('Bunyala Technical Training Institute', 'COL-013', 'Busia'),
            ('Bureti Technical Training Institute', 'COL-014', 'Kericho'),
            ('Bushiangala Technical Training Institute', 'COL-015', 'Kakamega'),
            ('Butere Technical and Vocational College', 'COL-016', 'Kakamega'),
            ('Butula Technical and Vocational College', 'COL-017', 'Busia'),
            ('Cardinal Maurice Otunga Technical and Vocational College', 'COL-018', 'Kisumu'),
            ('Centre for Tourism Training and Research', 'COL-019', 'Nairobi'),
            ('Chamasiri Technical and Vocational College', 'COL-020', 'Nairobi'),
            ('Chanzeywe Technical and Vocational College', 'COL-021', 'Mombasa'),
            ('Chepalungu Technical Training Institute', 'COL-022', 'Bomet'),
            ('Cherangany Technical and Vocational College', 'COL-023', 'Trans Nzoia'),
            ('Chepsirei Technical and Vocational College', 'COL-024', 'Uasin Gishu'),
            ('Chevaywa Technical and Vocational College', 'COL-025', 'Kakamega'),
            ('Chuka Technical and Vocational College', 'COL-026', 'Tharaka Nithi'),
            ('Chuka University TVET Igembe Campus', 'COL-027', 'Meru'),
            ('Coast Institute of Technology', 'COL-028', 'Mombasa'),
            ('Co-operative University of Kenya Nairobi CBD Training Institute', 'COL-029', 'Nairobi'),
            ('David M Wambuli Technical and Vocational College', 'COL-030', 'Kitui'),
            ('East Africa Institute of Certified Studies', 'COL-031', 'Nairobi'),
            ('East Africa School of Aviation', 'COL-032', 'Nairobi'),
            ('Ebukanga Technical and Vocational College', 'COL-033', 'Kakamega'),
            ('Ekerubo Gietai Technical Training Institute', 'COL-034', 'Nyamira'),
            ('Elwak Technical and Vocational College', 'COL-035', 'Mandera'),
            ('Emining Technical Training Institute', 'COL-036', 'Baringo'),
            ('Emsos Technical and Vocational College', 'COL-037', 'Elgeyo Marakwet'),
            ('Endebess Technical Training Institute', 'COL-038', 'Trans Nzoia'),
            ('Fayya Technical and Vocational College', 'COL-039', 'Wajir'),
            ('Garissa University TVET Institute', 'COL-040', 'Garissa'),
            ('Gatanga Technical and Vocational College', 'COL-041', "Murang'a"),
            ('Gatundu South Technical and Vocational College', 'COL-042', 'Kiambu'),
            ('Gilgil Technical and Vocational College', 'COL-043', 'Nakuru'),
            ('Githunguri Technical and Vocational College', 'COL-044', 'Kiambu'),
            ('Gitwebe Technical Training Institute', 'COL-045', 'Nyeri'),
            ('Godoma Technical Training Institute', 'COL-046', 'Meru'),
            ('Got Ramogi Technical and Vocational College', 'COL-047', 'Siaya'),
            ('Ijara Technical and Vocational College', 'COL-048', 'Garissa'),
            ('Ikutha Technical Training Institute', 'COL-049', 'Kitui'),
            ('Jomo Kenyatta University of Agriculture and Technology TVET Institute', 'COL-050', 'Kiambu'),
            ('Kabarak University TVET Institute', 'COL-051', 'Nakuru'),
            ('Kaelo Technical Training Institute', 'COL-052', 'Samburu'),
            ('Kajiado West Technical and Vocational College', 'COL-053', 'Kajiado'),
            ('Kakrao Technical and Vocational College', 'COL-054', 'Homa Bay'),
            ('Kaloleni Technical and Vocational College', 'COL-055', 'Kilifi'),
            ('Kamukunji Technical and Vocational College', 'COL-056', 'Nairobi'),
            ('Kapchepkor Technical Training Institute', 'COL-057', 'Elgeyo Marakwet'),
            ('Kapcherop Technical and Vocational College', 'COL-058', 'Elgeyo Marakwet'),
            ('Karen Technical Training Institute for the Deaf', 'COL-059', 'Nairobi'),
            ('Karumo Technical Training Institute', 'COL-060', 'Meru'),
            ('Kasarani Technical and Vocational College', 'COL-061', 'Nairobi'),
            ('KASNEB', 'COL-062', 'Nairobi'),
            ('Katine Technical Training Institute', 'COL-063', 'Busia'),
            ('Kendege Technical and Vocational College', 'COL-064', 'Kisii'),
            ('Kenya Forestry College', 'COL-065', 'Nyeri'),
            ('Kenya Industrial Training Institute', 'COL-066', 'Nairobi'),
            ('Kenya Institute of Highways and Building Technology', 'COL-067', 'Nairobi'),
            ('Kenya Institute of Mass Communication', 'COL-068', 'Nairobi'),
            ('Kenya Institute of Surveying and Mapping', 'COL-069', 'Nairobi'),
            ('Kenya Medical Training College', 'COL-070', 'Nairobi'),
            ('Kenya School of Agriculture Songa Mbele Campus', 'COL-071', 'Embu'),
            ('Kenya School of Law', 'COL-072', 'Nairobi'),
            ('Kenya School of Monetary Studies', 'COL-073', 'Nairobi'),
            ('Kenya School of Revenue Administration', 'COL-074', 'Nairobi'),
            ('Kenya School of TVET', 'COL-075', 'Nairobi'),
            ('Kenya Utalii College', 'COL-076', 'Nairobi'),
            ('Kenya Water Institute', 'COL-077', 'Nairobi'),
            ('Kenya Wildlife Service Training Institute', 'COL-078', 'Nairobi'),
            ('Kenyatta University City Campus TVET Centre', 'COL-079', 'Nairobi'),
            ('Kericho Township Technical and Vocational College', 'COL-080', 'Kericho'),
            ('Keroka Technical Training Institute', 'COL-081', 'Nyamira'),
            ('Kibabii University Directorate of TVET College', 'COL-082', 'Bungoma'),
            ('Kibwezi West Technical and Vocational College', 'COL-083', 'Makueni'),
            ('Kieni Technical and Vocational College', 'COL-084', 'Nyeri'),
            ('Kigumo Technical Training Institute', 'COL-085', "Murang'a"),
            ('Kiharu Technical and Vocational College', 'COL-086', "Murang'a"),
            ('Kiirua Technical Training Institute', 'COL-087', 'Meru'),
            ('Kilgoris Technical and Vocational College', 'COL-088', 'Narok'),
            ('Kimasian Technical and Vocational College', 'COL-089', 'Baringo'),
            ('Kiminini Technical and Vocational College', 'COL-090', 'Trans Nzoia'),
            ('Kinango Technical and Vocational College', 'COL-091', 'Kwale'),
            ('Kinangop Technical and Vocational College', 'COL-092', 'Nyandarua'),
            ('Kinoo Vocational Training Centre', 'COL-093', 'Kiambu'),
            ('Kipipiri Technical and Vocational College', 'COL-094', 'Nyandarua'),
            ('Kipkabus Technical and Vocational College', 'COL-095', 'Uasin Gishu'),
            ('Kipsinende Technical and Vocational College', 'COL-096', 'Elgeyo Marakwet'),
            ('Kipsoen Technical and Vocational College', 'COL-097', 'Bomet'),
            ('Kiptaragon Technical and Vocational College', 'COL-098', 'Baringo'),
            ('Kirinyaga Central Technical and Vocational College', 'COL-099', 'Kirinyaga'),
            ('Kisii University TVET Institute', 'COL-100', 'Kisii'),
            ('Kisiwa Technical Training Institute', 'COL-101', 'Siaya'),
            ('Kitelakapel Technical and Vocational College', 'COL-102', 'Samburu'),
            ('Kitui East Technical and Vocational College', 'COL-103', 'Kitui'),
            ('Kitui Rural Technical and Vocational College', 'COL-104', 'Kitui'),
            ('Kitutu Chache Technical and Vocational College', 'COL-105', 'Kisii'),
            ('Kongoni Technical and Vocational College', 'COL-106', 'Nakuru'),
            ('Konoin Technical Training Institute', 'COL-107', 'Bomet'),
            ('Koshin Technical Training Institute', 'COL-108', 'Marsabit'),
            ('Khwisero Technical and Vocational College', 'COL-109', 'Kakamega'),
            ('Lagdera Technical and Vocational College', 'COL-110', 'Garissa'),
            ('Laikipia East Technical and Vocational College', 'COL-111', 'Laikipia'),
            ('Laikipia North Technical and Vocational College', 'COL-112', 'Laikipia'),
            ('Laikipia West Technical and Vocational College', 'COL-113', 'Laikipia'),
            ('Laikipia University TVET Institute', 'COL-114', 'Laikipia'),
            ('Laisamis Technical and Vocational College', 'COL-115', 'Marsabit'),
            ('Lamu East Technical and Vocational College', 'COL-116', 'Lamu'),
            ('Langata Technical and Vocational College', 'COL-117', 'Nairobi'),
            ('Lari Technical and Vocational College', 'COL-118', 'Kiambu'),
            ('Limuru Technical Vocational College', 'COL-119', 'Kiambu'),
            ('Lodwar Technical and Vocational College', 'COL-120', 'Turkana'),
            ('Loima Technical and Vocational College', 'COL-121', 'Turkana'),
            ('Lungalunga Technical Vocational College', 'COL-122', 'Kwale'),
            ('Maasai Mara Technical and Vocational Training College', 'COL-123', 'Narok'),
            ('Maasai Mara University TVET Institute', 'COL-124', 'Narok'),
            ('Mabera Technical and Vocational College', 'COL-125', 'Nyamira'),
            ('Machakos Technical Institute for the Blind', 'COL-126', 'Machakos'),
            ('Machakos Township Technical and Vocational College', 'COL-127', 'Machakos'),
            ('Manyatta Technical Vocational College', 'COL-128', 'Embu'),
            ('Marist Technical Vocational College', 'COL-129', 'Nairobi'),
            ('Masinga Technical and Vocational College', 'COL-130', 'Machakos'),
            ('Mathenge Technical Training Institute', 'COL-131', 'Nyeri'),
            ('Mathioya Technical and Vocational College', 'COL-132', "Murang'a"),
            ('Mathira Technical and Vocational College', 'COL-133', 'Nyeri'),
            ('Matili Technical Training Institute', 'COL-134', 'Kakamega'),
            ('Mbeere North Technical and Vocational College', 'COL-135', 'Embu'),
            ('Mbita Technical and Vocational College', 'COL-136', 'Homa Bay'),
            ('Merti Technical Training Institute', 'COL-137', 'Isiolo'),
            ('Meru University of Science and Technology TVET Directorate', 'COL-138', 'Meru'),
            ('Michuki Technical Training Institute', 'COL-139', "Murang'a"),
            ('Mitunguu Technical Training Institute', 'COL-140', 'Meru'),
            ('Mochoi Technical and Vocational College', 'COL-141', 'Nakuru'),
            ('Mochongoi Technical and Vocational College', 'COL-142', 'Baringo'),
            ('Moi University TVET Institute', 'COL-143', 'Uasin Gishu'),
            ('Moiben Technical and Vocational College', 'COL-144', 'Uasin Gishu'),
            ('Molo Technical and Vocational College', 'COL-145', 'Nakuru'),
            ('Morendat Institute of Oil and Gas', 'COL-146', 'Nakuru'),
            ('Msambweni Technical and Vocational College', 'COL-147', 'Kwale'),
            ('Mukiria Technical Training Institute', 'COL-148', 'Meru'),
            ('Mukurwe-ini Technical Training Institute', 'COL-149', 'Nyeri'),
            ('Mulango Technical and Vocational College', 'COL-150', 'Kitui'),
            ('Mumias West Technical and Vocational College', 'COL-151', 'Kakamega'),
            ('Mungatsi Technical and Vocational College', 'COL-152', 'Kakamega'),
            ("Murang'a Technical Training Institute", 'COL-153', "Murang'a"),
            ("Murang'a University of Technology TVET Institute", 'COL-154', "Murang'a"),
            ('Musakasa Technical Training Institute', 'COL-155', 'Kakamega'),
            ('Mwala Technical and Vocational College', 'COL-156', 'Machakos'),
            ('Mwatate Technical and Vocational College', 'COL-157', 'Taita Taveta'),
            ('Mwea Technical and Vocational College', 'COL-158', 'Kirinyaga'),
            ('Nachu Technical and Vocational College', 'COL-159', 'Kiambu'),
            ('Naivasha Technical and Vocational College', 'COL-160', 'Nakuru'),
            ('Narok South Technical and Vocational College', 'COL-161', 'Narok'),
            ('Ndaragwa Technical and Vocational College', 'COL-162', 'Nyandarua'),
            ('Ndia Technical and Vocational College', 'COL-163', 'Kirinyaga'),
            ('Ngeria Technical and Vocational College', 'COL-164', 'Uasin Gishu'),
            ('Ngong Technical and Vocational College', 'COL-165', 'Kajiado'),
            ('Njoro Technical Training Institute', 'COL-166', 'Nakuru'),
            ('Nkabune Technical Training Institute', 'COL-167', 'Meru'),
            ('North Horr Technical and Vocational College', 'COL-168', 'Marsabit'),
            ('North Rift Technical and Vocational College', 'COL-169', 'Turkana'),
            ('Nuu Technical and Vocational College', 'COL-170', 'Kitui'),
            ('Nyaga Vocational Training Centre', 'COL-171', 'Tharaka Nithi'),
            ('Nyakach Technical and Vocational College', 'COL-172', 'Kisumu'),
            ('Nyando Technical Training Institute', 'COL-173', 'Kisumu'),
            ('Okame Technical Training Institute', 'COL-174', 'Homa Bay'),
            ('Ol Kalou Technical and Vocational College', 'COL-175', 'Nyandarua'),
            ('Omuga Technical and Vocational College', 'COL-176', 'Vihiga'),
            ('P.C Kinyanjui Technical Training Institute', 'COL-177', 'Nairobi'),
            ('Rachuonyo Technical and Vocational College', 'COL-178', 'Homa Bay'),
            ('Railway Training Institute', 'COL-179', 'Nairobi'),
            ('Ramogi Institute of Advanced Technology', 'COL-180', 'Siaya'),
            ('Rangwe Technical and Vocational College', 'COL-181', 'Homa Bay'),
            ('Rarieda Technical and Vocational College', 'COL-182', 'Siaya'),
            ('Riamo Technical and Vocational College', 'COL-183', 'Kisii'),
            ('Riatirimba Technical and Vocational College', 'COL-184', 'Nyamira'),
            ('Rift Valley Institute of Science and Technology', 'COL-185', 'Nakuru'),
            ('Rift Valley Technical Training Institute', 'COL-186', 'Nakuru'),
            ('Rongo University Technical and Vocational Training Institute', 'COL-187', 'Migori'),
            ('Ruiru Technical and Vocational College', 'COL-188', 'Kiambu'),
            ('Runyenjes Technical and Vocational College', 'COL-189', 'Embu'),
            ('Rwika Technical Institute', 'COL-190', 'Meru'),
            ('Sabatia Technical and Vocational College', 'COL-191', 'Vihiga'),
            ('Samburu North Technical and Vocational College', 'COL-192', 'Samburu'),
            ('Samburu Technical and Vocational College', 'COL-193', 'Samburu'),
            ('Seme Technical and Vocational College', 'COL-194', 'Kisumu'),
            ('Siala Technical Training Institute', 'COL-195', 'Homa Bay'),
            ('Sirisia Technical and Vocational College', 'COL-196', 'Bungoma'),
            ('Siruti Technical and Vocational College', 'COL-197', 'Kakamega'),
            ('Sot Technical Training Institute', 'COL-198', 'Baringo'),
            ('Sotik Technical Training Institute', 'COL-199', 'Kericho'),
            ('South Eastern Kenya University SEKU Directorate of TVET', 'COL-200', 'Kitui'),
            ("St. Joseph's Technical Institute for the Deaf Nyang'oma", 'COL-201', 'Siaya'),
            ('Subukia Technical and Vocational College', 'COL-202', 'Nakuru'),
            ('Taita Taveta University Institute of TVET', 'COL-203', 'Taita Taveta'),
            ('Tarbaj Technical and Vocational College', 'COL-204', 'Wajir'),
            ('Technology Development Centre Athi River', 'COL-205', 'Machakos'),
            ('Tetu Technical and Vocational College', 'COL-206', 'Nyeri'),
            ('Technical University of Kenya TUK Directorate of TVET College', 'COL-207', 'Nairobi'),
            ('Technical University of Mombasa TUM TVET Institute', 'COL-208', 'Mombasa'),
            ('Tharaka Technical and Vocational College', 'COL-209', 'Tharaka Nithi'),
            ('Tharaka University TVET Institute', 'COL-210', 'Tharaka Nithi'),
            ("The Ol'lessos Technical Training Institute", 'COL-211', 'Nandi'),
            ('The University of Embu TVET Institute', 'COL-212', 'Embu'),
            ('Thika Technical Training Institute', 'COL-213', 'Kiambu'),
            ('Thogoto Vocational Training Centre', 'COL-214', 'Kiambu'),
            ('Tinderet Integrated Technical and Trainers College', 'COL-215', 'Nandi'),
            ('Tom Mboya Labour College', 'COL-216', 'Homa Bay'),
            ('Turkana East Technical and Vocational College', 'COL-217', 'Turkana'),
            ('Turkana University College TVET Institute', 'COL-218', 'Turkana'),
            ('Ugenya Technical and Vocational College', 'COL-219', 'Siaya'),
            ('Ugunja Technical and Vocational College', 'COL-220', 'Siaya'),
            ('Uriri Technical and Vocational College', 'COL-221', 'Migori'),
            ('Wajir East Technical and Vocational College', 'COL-222', 'Wajir'),
            ('Wajir South Technical and Vocational College', 'COL-223', 'Wajir'),
            ('Watamu Technical and Vocational College', 'COL-224', 'Kilifi'),
            ('Webuye West Technical and Vocational College', 'COL-225', 'Bungoma'),
            ('Weru Technical and Vocational College', 'COL-226', 'Meru'),
            ('West Mugirango Technical and Vocational College', 'COL-227', 'Nyamira'),
            ('Wote Technical Training Institute', 'COL-228', 'Makueni'),
            ('Wumingu Technical and Vocational College', 'COL-229', 'Meru'),
            ('Ziwa Technical Training Institute', 'COL-230', 'Nyeri'),
            ('African Institute of Research and Development Studies', 'COL-231', 'Nairobi'),
            ('Beauty Point College', 'COL-232', 'Nairobi'),
            ('Bishop Locati Technical Training Institute', 'COL-233', 'Nakuru'),
            ('Bridgeworld College', 'COL-234', 'Nairobi'),
            ('Cascade Institute of Hospitality', 'COL-235', 'Nairobi'),
            ('Clastars College', 'COL-236', 'Nairobi'),
            ('College of Human Resource Management', 'COL-237', 'Nairobi'),
            ('Embu College', 'COL-238', 'Embu'),
            ('Equip Africa College of Medical and Health Sciences', 'COL-239', 'Nairobi'),
            ('Equip Africa Institute', 'COL-240', 'Nairobi'),
            ('Gretsa Institute of Technical and Professional Studies', 'COL-241', 'Kiambu'),
            ('Hemland College of Professional and Technical Studies', 'COL-242', 'Nairobi'),
            ('Highlands State Technical College', 'COL-243', 'Nakuru'),
            ('ICDL Africa Ltd', 'COL-244', 'Nairobi'),
            ('JFC Munene College', 'COL-245', 'Meru'),
            ('Joan School of Nursing', 'COL-246', 'Nairobi'),
            ('Jodan College of Technology', 'COL-247', 'Nairobi'),
            ('KAN College of Professional Studies', 'COL-248', 'Nairobi'),
            ('KCA Technical College', 'COL-249', 'Nairobi'),
            ('Kenya Aeronautical College', 'COL-250', 'Nairobi'),
            ('Kenya Christian Industrial Training Institute', 'COL-251', 'Nairobi'),
            ('Kenya Institute of Management', 'COL-252', 'Nairobi'),
            ('Kenya Institute of Social Work and Community Development', 'COL-253', 'Nairobi'),
            ('Kenya School of Medical Science and Technology', 'COL-254', 'Nairobi'),
            ('Kenya YMCA College of Agriculture and Technology', 'COL-255', 'Nairobi'),
            ('KIPS Technical College', 'COL-256', 'Nairobi'),
            ('Machakos Institute of Technology', 'COL-257', 'Machakos'),
            ('Mahanaim Educational Institute', 'COL-258', 'Nairobi'),
            ('Maseno School of Nursing and Health Sciences', 'COL-259', 'Kisumu'),
            ('Nairobi Aviation College', 'COL-260', 'Nairobi'),
            ('Nairobi College of Bread and Confectionery Technology', 'COL-261', 'Nairobi'),
            ('Nairobi Institute of Technology', 'COL-262', 'Nairobi'),
            ('Nairobi Technical Training Institute', 'COL-263', 'Nairobi'),
            ("Nairobi Women's Hospital College", 'COL-264', 'Nairobi'),
            ('Nakuru Training Institute', 'COL-265', 'Nakuru'),
            ('Oshwal College', 'COL-266', 'Nairobi'),
            ('Outspan Medical College', 'COL-267', 'Nyeri'),
            ('Rift Valley Institute of Business Studies', 'COL-268', 'Nakuru'),
            ('Sagana Technical Training Institute', 'COL-269', 'Kirinyaga'),
            ('Sensei Institute of Technology', 'COL-270', 'Nairobi'),
            ('SOS Technical Training Institute', 'COL-271', 'Nairobi'),
            ('Span Institute of Technology', 'COL-272', 'Nairobi'),
            ("St. Columba's Technical Training College", 'COL-273', 'Nairobi'),
            ('Stanbridge College', 'COL-274', 'Nairobi'),
            ('Technical Institute', 'COL-275', 'Nairobi'),
            ('Traction School of Governance and Business', 'COL-276', 'Nairobi'),
            ('Transafric Accountancy and Management College', 'COL-277', 'Nairobi'),
            ('Tropical Institute of Community Health', 'COL-278', 'Nairobi'),
            ('Uwezo College', 'COL-279', 'Nairobi'),
            ('Vera Beauty College', 'COL-280', 'Nairobi'),
            ('VICODEC Technical Training Institute', 'COL-281', 'Nairobi'),
            ('Vihiga College of Business and Technical Training', 'COL-282', 'Vihiga'),
            ('Vitech Training Institute', 'COL-283', 'Nairobi'),
        ]

        for name, code, county in colleges:
            school, created = School.objects.get_or_create(
                registration_number=code,
                defaults={'name': name, 'school_type': 'college', 'county': county}
            )
            if created:
                Campus.objects.get_or_create(school=school, name='Main Campus',
                                             defaults={'location': county, 'is_main': True})
                created_total += 1

        self.stdout.write(self.style.SUCCESS(f'Colleges done.'))

        # ─────────────────────────────────────────────────────────
        # NATIONAL POLYTECHNICS
        # ─────────────────────────────────────────────────────────
        polytechnics = [
            ('Baringo National Polytechnic', 'POLY-001', 'Baringo'),
            ('Bumbe National Polytechnic', 'POLY-002', 'Busia'),
            ('Bungoma National Polytechnic', 'POLY-003', 'Bungoma'),
            ('Bureti National Polytechnic', 'POLY-004', 'Kericho'),
            ('Eldoret National Polytechnic', 'POLY-005', 'Uasin Gishu'),
            ('Friends National Polytechnic Kaimosi', 'POLY-006', 'Vihiga'),
            ('Jeremiah Nyagah National Polytechnic', 'POLY-007', 'Embu'),
            ('Kabete National Polytechnic', 'POLY-008', 'Nairobi'),
            ('Kaiboi National Polytechnic', 'POLY-009', 'Nandi'),
            ('Kenya Coast National Polytechnic', 'POLY-010', 'Mombasa'),
            ('Kiambu National Polytechnic', 'POLY-011', 'Kiambu'),
            ('Kisii National Polytechnic', 'POLY-012', 'Kisii'),
            ('Kisumu National Polytechnic', 'POLY-013', 'Kisumu'),
            ('Kitale National Polytechnic', 'POLY-014', 'Trans Nzoia'),
            ('Maasai National Polytechnic', 'POLY-015', 'Kajiado'),
            ('Mawego National Polytechnic', 'POLY-016', 'Homa Bay'),
            ('Meru National Polytechnic', 'POLY-017', 'Meru'),
            ('Morendat Institute of Oil and Gas National Polytechnic', 'POLY-018', 'Nakuru'),
            ('Nairobi National Polytechnic', 'POLY-019', 'Nairobi'),
            ('North Eastern National Polytechnic', 'POLY-020', 'Garissa'),
            ('Nyandarua National Polytechnic', 'POLY-021', 'Nyandarua'),
            ('Nyeri National Polytechnic', 'POLY-022', 'Nyeri'),
            ('Siaya National Polytechnic', 'POLY-023', 'Siaya'),
            ('Sigalagala National Polytechnic', 'POLY-024', 'Kakamega'),
            ('Shamberere National Polytechnic', 'POLY-025', 'Kakamega'),
        ]

        for name, code, county in polytechnics:
            school, created = School.objects.get_or_create(
                registration_number=code,
                defaults={'name': name, 'school_type': 'polytechnic', 'county': county}
            )
            if created:
                Campus.objects.get_or_create(school=school, name='Main Campus',
                                             defaults={'location': county, 'is_main': True})
                created_total += 1

        self.stdout.write(self.style.SUCCESS(f'National Polytechnics done.'))

        # ─────────────────────────────────────────────────────────
        # TEACHERS TRAINING COLLEGES (TTC)
        # ─────────────────────────────────────────────────────────
        ttcs = [
            ('Asumbi Teachers Training College', 'TTC-001', 'Homa Bay'),
            ('Bishop Mahon Teachers Training College', 'TTC-002', 'Kisii'),
            ('Bunyore Teachers Training College', 'TTC-003', 'Vihiga'),
            ('Galana Teachers Training College', 'TTC-004', 'Kilifi'),
            ('Garissa Teachers Training College', 'TTC-005', 'Garissa'),
            ('Kagumo Teachers Training College', 'TTC-006', 'Nyeri'),
            ('Kaimosi Teachers Training College', 'TTC-007', 'Vihiga'),
            ('Kericho Teachers Training College', 'TTC-008', 'Kericho'),
            ('Kibabii Diploma Teachers Training College', 'TTC-009', 'Bungoma'),
            ('Kitui Teachers Training College', 'TTC-010', 'Kitui'),
            ('Kwale Teachers Training College', 'TTC-011', 'Kwale'),
            ('Lugari Teachers Training College', 'TTC-012', 'Kakamega'),
            ('Meru Teachers Training College', 'TTC-013', 'Meru'),
            ('Narok Teachers Training College', 'TTC-014', 'Narok'),
            ('Rachuonyo Teachers Training College', 'TTC-015', 'Homa Bay'),
            ('Seme Teachers Training College', 'TTC-016', 'Kisumu'),
            ("St. Augustine Teacher's Training College Eregi", 'TTC-017', 'Kakamega'),
            ('Tambach Teachers Training College', 'TTC-018', 'Elgeyo Marakwet'),
            ('Vantage Teachers Training College', 'TTC-019', 'Nairobi'),
        ]

        for name, code, county in ttcs:
            school, created = School.objects.get_or_create(
                registration_number=code,
                defaults={'name': name, 'school_type': 'ttc', 'county': county}
            )
            if created:
                Campus.objects.get_or_create(school=school, name='Main Campus',
                                             defaults={'location': county, 'is_main': True})
                created_total += 1

        self.stdout.write(self.style.SUCCESS(f'Teachers Training Colleges done.'))
        self.stdout.write(self.style.SUCCESS(
            f'Total new schools added: {created_total}. '
            f'Total in database: {School.objects.count()}'
        ))
